version: '3'
services:
  bff:
    build:
      context: ./apps/bff
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file: .env.production.local

  ui:
    build:
      context: ./apps/ui
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_BASE=http://localhost:8080
        - API_BASE=http://bff:8080
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:8080
      - API_BASE=http://bff:8080